config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  resources :articles
  resources :users_admin, controller: :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user

	validates_presence_of :user, :title, :content, :category
	validates :category, inclusion: { in: ['Art', 'Business', 'Finance', 'Health', 'Politics'],
    message: "%{value} is not a category" }
    validates :title, length: { minimum: 2 }
  	validates :content, length: { maximum: 500 }

    def self.categories
    	['Art', 'Business', 'Finance', 'Health', 'Politics']
    end

    def is_author?(current_user)
    	self.user == current_user
    end

    def self.recent_articles
    	group(:category).limit(3)
    end
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin, :editor], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :email

  has_many :articles,  dependent: :destroy


  def authorized_to_create_articles?
    return [:editor].include? self.role
  end

  def authorized_to_view_articles?
    return [:user, :admin, :editor].include? self.role
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user!, except: [:index]
	access all: [:index], [:user, :admin] =>  {except: [:new, :create, :edit, :update, :destroy]} , editor: :all

	def index
		@articles = Article.includes(:user)
	end

	def new
		@article = Article.new
	end

	def create
		@article = Article.new(article_params)
		@article.user = current_user
	  if @article.save
	    redirect_to @article
	  else
	    render 'new'
	  end
	end

	def show
		@article = Article.find(params[:id])
		redirect_to root_url, flash: { error: "Record not found." } if @article.blank?
	end

	def edit
		@article = Article.find_by(id: params[:id], user: current_user)
  		redirect_to root_url, flash: { error: "Record not found." } if @article.blank?
	end

	def update
		@article = Article.find_by(id: params[:id], user: current_user)
		redirect_to root_url, flash: { error: "Record not found." } if @article.blank?
		if @article.update(article_params)
		   	redirect_to @article
		else
		    render 'edit'
		end
	end

	def destroy
		@article = Article.find_by(id: params[:id], user: current_user)
		redirect_to root_url, flash: { error: "Record not found." } if @article.blank?

  		@article.destroy
  		redirect_to articles_path
	end

	private
	def article_params
		params.require(:article).permit(:title, :content, :category)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@articles = Article.recent_articles
		render :index
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	access admin: :all

	def index
		@users = User.all
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
	 	if @user.save
	    	redirect_to users_admin_path(@user)
	  	else
	    	render 'new'
	  	end
	end

	def show
		@user = User.find(params[:id])
		redirect_to root_url, flash: { error: "User not found." } if @user.blank?
	end

	def edit
		@user = User.find(params[:id])
  		redirect_to root_url, flash: { error: "User not found." } if @user.blank?
	end

	def update
		@user = User.find(params[:id])
		redirect_to root_url, flash: { error: "User not found." } if @user.blank?
		if @user.update(user_params)
		   	redirect_to users_admin_path(@user)
		else
		    render 'edit'
		end
	end

	def destroy
		@user = User.find_by(id: params[:id])
		redirect_to root_url, flash: { error: "User not found." } if @user.blank?

  		@user.destroy
  		redirect_to users_admin_path(@user)
	end

	private
	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation, :roles)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :category %><br>
    <%= form.select :category, Article.categories %>
  </p>
  <p>
    <%= form.label :content %><br>
    <%= form.text_area :content %>
  </p>

  <p>
    <%= form.submit %>
  </p>

app/views/articles/_index.html.erb
<table>
  <tr>
    <th>Title</th>
    <th>Category</th>
    <th>Content</th>
    <th>User</th>
    <th colspan="2"></th>
  </tr>

  <% articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.category %></td>
      <td><%= article.content %></td>
      <td><%= article.user.email %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_article_path(article) if article.is_author?(current_user) %></td>
        <td><%= link_to 'Destroy', article_path(article), method: :delete, data: { confirm: 'Are you sure?' } if article.is_author?(current_user) %>
         </td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
 
<%= form_with(model: @article, local: true) do |form| %>
  <%= render partial: 'form', locals: { article: @article, form: form } %>
<% end %>

app/views/articles/index.html.erb
<h1>All Articles</h1>
<%= render partial: 'index', locals: { articles: @articles } %>

app/views/articles/new.html.erb
<h1>New Article</h1>
<%= form_with scope: @article, url: articles_path, local: true do |form| %>
	<%= render partial: 'form', locals: { article: @article, form: form } %>
<% end %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
<p>
  <strong>Category:</strong>
  <%= @article.category %>
</p>
<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>
<p>
  <strong>User:</strong>
  <%= @article.user.email %>
</p>

app/views/home/index.html.erb
<% if @articles.blank? %>
	<h3>No Articles today</h3>
<% else %>
	<h1>Recent Articles</h1>
	<%= render partial: 'articles/index', locals: { articles: @articles } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AndrewgarciaRorCompetencyTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>


  <body style="padding-top: 75px;">
    <%= render template: 'layouts/navbar' %>
    <div class="container">
      <% if flash[:error] %>
        <div class="alert alert-danger" role="alert">
          <p><%= flash[:error] %></p>
        </div>
        
      <% end %>
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/layouts/navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light fixed-top bg-light">
  <div class="container">
    <a class="navbar-brand mb-0 h1" href='/'>Articles</a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown Menu
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'View All Articles', articles_path, class: "dropdown-item"  %>

          <% if user_signed_in? %>

            <%= link_to 'New Article', new_article_path, class: "dropdown-item" if logged_in?(:editor) %>
            <% if logged_in?(:admin) %>
              <%= link_to 'Users', users_admin_index_path, class: "dropdown-item"  %>
              <%= link_to 'Users', new_users_admin_path, class: "dropdown-item"  %>
            <% end %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "dropdown-item" %>

          <% else %>

          <%= link_to 'Log In', new_user_session_path, class: "dropdown-item" %>
          <%= link_to 'Sign Up', new_user_registration_path, class: "dropdown-item" %>
          <% end %>

        </div>
      </li>
    </ul>
  </div>
  <% if user_signed_in? %>
    <span class="mb-0">Logged in as: <%= current_user.email %></span>
  <% end %>
</nav>

app/views/users/_form.html.erb
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :email %><br>
    <%= form.email_field :email %>
  </p>
  <p>
    <%= form.label :password %><br>
    <%= form.password_field :password %>
  </p>
   <p>
    <%= form.label :password_confirmation %><br>
    <%= form.password_field :password_confirmation %>
  </p>
  <p>
    <%= form.label :roles %><br>
    <%= form.select :roles, User::ROLES %>
  </p>
  <p>
  <p>
    <%= form.submit %>
  </p>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<%= form_for @user, url: users_admin_path(@user), method: :patch  do |form| %>
	<%= render partial: 'form', locals: { user: @user, form: form } %>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>
<td><%= link_to 'Create User', new_users_admin_path %>
<table>
  <tr>
    <th>User</th>
    <th>Roles</th>
    <th colspan="2"></th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.email %></td>
      <td><%= user.roles.join(', ') %></td>
      <td><%= link_to 'Show', users_admin_path(user) %></td>
      <td><%= link_to 'Edit', edit_users_admin_path(user) %></td>
      <td><%= link_to 'Destroy', users_admin_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
<h1>New User</h1>
<%= form_for @user, url: users_admin_index_path(@user) do |form| %>
	<%= render partial: 'form', locals: { user: @user, form: form } %>
<% end %>

app/views/users/show.html.erb
<p>User email: <%= @user.email %></p>
<p>User roles: <%= @user.roles %></p>